# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.10
  hooks:
    - id: insert-license
      args: [--license-filepath, LICENSE]
      types: [python]
- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v1.19.0
  hooks:
    - id: setup-cfg-fmt
- repo: https://github.com/PyCQA/isort
  rev: 5.10.0
  hooks:
    - id: isort
- repo: https://github.com/myint/autoflake
  rev: v1.4
  hooks:
    - id: autoflake
      args: [--in-place, --remove-unused-variables, --remove-all-unused-imports, --remove-duplicate-keys]
- repo: https://github.com/python/black
  rev: 21.10b0
  hooks:
    - id: black
    - id: black
      name: black (pyi)
      types: [pyi]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910-1
  hooks:
    - id: mypy
      additional_dependencies:
        - fastapi>=0.63.0
        - pydantic>=1.8
        - starlette>=0.12.0
        - libtorrent>=2.0.4
        - types-cachetools
        - types-requests
        # keep this part in sync with tvaf/tests/test-requirements.txt
        - importlib-resources>=3.3.0
        - asgi-lifespan>=1.0.0,<2
        - later>=20.2.1
        - httpx>=0.20.0,<0.21
- repo: https://gitlab.com/pycqa/flake8.git
  rev: 3.9.2
  hooks:
    - id: flake8
      additional_dependencies: [flake8-2020, flake8-bugbear, flake8-comprehensions, flake8-logging-format, flake8-mutable, pep8-naming, flake8-tidy-imports, flake8-annotations-coverage]
- repo: https://gitlab.com/pycqa/pydocstyle.git
  rev: 6.1.1
  hooks:
    - id: pydocstyle
      exclude: |
        (?x)^(
          .*/test_.*\.py|
          tvaf/driver.py|
          tvaf/__init__.py|
          tvaf/lifecycle.py|
          tvaf/ltmodels.py|
          tvaf/ltpy.py|
          tvaf/multihash.py|
          tvaf/plugins.py|
          tvaf/request.py|
          tvaf/resume.py|
          tvaf/routers/config.py|
          tvaf/routers/data.py|
          tvaf/routers/__init__.py|
          tvaf/routers/torrent.py|
          tvaf/services/__init__.py|
          tvaf/services/util.py|
          tvaf/session.py|
          tvaf/spaceman.py|
          tvaf/tests/data/__init__.py|
          tvaf/tests/__init__.py|
          tvaf/tests/lib.py|
          tvaf/tests/mock_time.py|
          tvaf/tests/request_test_utils.py|
          tvaf/tests/tdummy.py|
          tvaf/torrent_info.py|
          tvaf/util.py|
          tvaf/xmemoryview.py
        )$
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: check-yaml
    - id: check-toml
    - id: check-merge-conflict
    - id: check-executables-have-shebangs
