# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.9
  hooks:
    - id: insert-license
      args: [--license-filepath, LICENSE]
      types: [python]
- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v1.15.1
  hooks:
    - id: setup-cfg-fmt
- repo: https://github.com/PyCQA/isort
  rev: 5.6.4
  hooks:
    - id: isort
- repo: https://github.com/myint/autoflake
  rev: v1.4
  hooks:
    - id: autoflake
      args: [--in-place, --remove-unused-variables, --remove-all-unused-imports, --remove-duplicate-keys]
- repo: https://github.com/python/black
  rev: 20.8b1
  hooks:
    - id: black
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.790
  hooks:
    - id: mypy
      name: mypy36
      language_version: python3.6
      additional_dependencies:
        - importlib_resources>=3.3.0
    - id: mypy
      name: mypy37
      language_version: python3.7
      additional_dependencies:
        - importlib_resources>=3.3.0
    - id: mypy
      name: mypy38
      language_version: python3.8
      additional_dependencies:
        - importlib_resources>=3.3.0
    - id: mypy
      name: mypy39
      language_version: python3.9
      additional_dependencies:
        - importlib_resources>=3.3.0
- repo: https://gitlab.com/pycqa/flake8.git
  rev: 3.8.4
  hooks:
    - id: flake8
      name: flake8_36
      language_version: python3.6
      #additional_dependencies: [flake8-2020, flake8-bugbear, flake8-comprehensions, flake8-eradicate, flake8-logging-format, flake8-mutable, pep8-naming, flake8-tidy-imports, flake8-annotations-coverage]
      additional_dependencies: [flake8-2020, flake8-bugbear, flake8-comprehensions, flake8-logging-format, flake8-mutable, flake8-tidy-imports]
    - id: flake8
      name: flake8_37
      language_version: python3.7
      additional_dependencies: [flake8-2020, flake8-bugbear, flake8-comprehensions, flake8-logging-format, flake8-mutable, flake8-tidy-imports]
    - id: flake8
      name: flake8_38
      language_version: python3.8
      additional_dependencies: [flake8-2020, flake8-bugbear, flake8-comprehensions, flake8-logging-format, flake8-mutable, flake8-tidy-imports]
    - id: flake8
      name: flake8_39
      language_version: python3.9
      additional_dependencies: [flake8-2020, flake8-bugbear, flake8-comprehensions, flake8-logging-format, flake8-mutable, flake8-tidy-imports]
    - id: flake8
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: check-yaml
    - id: check-toml
    - id: check-merge-conflict
    - id: check-executables-have-shebangs
