name: ci
on:
  pull_request:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        py: [ "3.9", "3.10" ]
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.py }}
      - run: |
          pip install --upgrade pip
          pip install tox
      - run: tox -- --log-level=DEBUG
      - uses: codecov/codecov-action@v3
  pre-commit:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        py: [ "3.9", "3.10" ]
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.py }}
      - run: |
          pip install --upgrade pip
          pip install pre-commit
      - id: homedir
        run:  echo "::set-output name=homedir::$HOME"
      - uses: actions/cache@v3
        with:
          path: ${{ steps.homedir.outputs.homedir }}/.cache/pre-commit
          key: pre-commit-${{ matrix.py }}-${{ matrix.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
      - run: pre-commit run -a --show-diff-on-failure --color=always
